# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: \n"
"POT-Creation-Date: 2019-12-14 18:13-0400\n"
"PO-Revision-Date: 2020-02-22 12:42+0800\n"
"Last-Translator: \n"
"Language-Team: \n"
"Language: zh\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.5\n"
"X-Generator: Poedit 2.3\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: analyze_syntax.py:60
msgid ""
"Python gave us the following informative message\n"
"about the possible cause of the error:\n"
"\n"
"    {message}\n"
"\n"
"However, I do not recognize this information and I have\n"
"to guess what caused the problem, but I might be wrong.\n"
"\n"
msgstr ""
"关于错误的原因，Python给出了以下提示信息：\n"
"\n"
"    {message}\n"
"\n"
"不过，我不太理解这个信息，只能尽量猜测导致错误的原因，\n"
"也有可能不准确。\n"
"\n"

#: analyze_syntax.py:68
msgid ""
"I make an effort below to guess what caused the problem\n"
"but I might guess incorrectly.\n"
"\n"
msgstr ""
"我尽量猜测导致错误的原因\n"
"但也有可能不准确。\n"
"\n"

#: analyze_syntax.py:96
msgid ""
"Currently, I cannot guess the likely cause of this error.\n"
"Try to examine closely the line indicated as well as the line\n"
"immediately above to see if you can identify some misspelled\n"
"word, or missing symbols, like (, ), [, ], :, etc.\n"
"\n"
"You might want to report this case to\n"
"https://github.com/aroberge/friendly-traceback/issues\n"
"\n"
msgstr ""
"目前我无法猜测这个错误的可能原因。\n"
"可以检查一下出错代码行前后，看看有没有拼写错误，\n"
"或者少了什么符号，比如括号、冒号这些：(, ), [, ], :。\n"
"\n"

#: analyze_type_error.py:32
msgid ""
"I do not recognize this case. Please report it to\n"
"https://github.com/aroberge/friendly-traceback/issues\n"
msgstr "抱歉，我不太确定这是啥情况。\n"

#: analyze_type_error.py:41
msgid "a complex number"
msgstr "1个复数（complex）"

#: analyze_type_error.py:43
msgid "a dictionary ('dict')"
msgstr "1个字典(“dict”)"

#: analyze_type_error.py:45
msgid "a number ('float')"
msgstr "1个浮点数（“float”）"

#: analyze_type_error.py:47
msgid "an integer ('int')"
msgstr "1个整数（“int”）"

#: analyze_type_error.py:49
msgid "a list"
msgstr "1个列表（“list”）"

#: analyze_type_error.py:51
msgid "a variable equal to None ('NoneType')"
msgstr "1个等于None（“NoneType”类型）的变量"

#: analyze_type_error.py:53
msgid "a set"
msgstr "1个集合（“set”）"

#: analyze_type_error.py:55
msgid "a string ('str')"
msgstr "1个字符串（“str”）"

#: analyze_type_error.py:57
msgid "a tuple"
msgstr "1个元组（“tuple”）"

#: analyze_type_error.py:72 analyze_type_error.py:90
msgid ""
"You tried to concatenate (add) two different types of objects:\n"
"{first} and {second}\n"
msgstr ""
"你想把两个不同类型的对象加（+）起来：\n"
"{first} 和 {second}\n"
"不同类型的对象不能简单就相加\n"

#: analyze_type_error.py:109
msgid ""
"You tried to add two incompatible types of objects:\n"
"{first} and {second}\n"
msgstr ""
"你想把两个不兼容类型的对象相加（+）：\n"
"{first} 和 {second}\n"
"不兼容的类型不能相加。\n"

#: analyze_type_error.py:116
msgid ""
"You tried to subtract two incompatible types of objects:\n"
"{first} and {second}\n"
msgstr ""
"你想把两个不兼容类型的对象相减（-）：\n"
"{first} 和 {second}\n"
"不兼容的类型不能相减。\n"

#: analyze_type_error.py:123
msgid ""
"You tried to multiply two incompatible types of objects:\n"
"{first} and {second}\n"
msgstr ""
"你想把两个不兼容类型的对象相乘（*）：\n"
"{first} 和 {second}\n"
"不兼容的类型不能相乘。\n"

#: analyze_type_error.py:130
msgid ""
"You tried to divide two incompatible types of objects:\n"
"{first} and {second}\n"
msgstr ""
"你想把两个不兼容类型的对象相除（/）：\n"
"{first} 和 {second}\n"
"不兼容的类型不能相除。\n"

#: analyze_type_error.py:137
msgid ""
"You tried to perform the bitwise operation {operator}\n"
"on two incompatible types of objects:\n"
"{first} and {second}\n"
msgstr ""
"你想把两个不兼容类型的对象做按位操作（{operator}）：\n"
"{first} 和 {second}\n"
"不兼容的类型不能做按位操作。\n"

#: analyze_type_error.py:147
msgid ""
"You tried to perform the bit shifting operation {operator}\n"
"on two incompatible types of objects:\n"
"{first} and {second}\n"
msgstr ""
"你想把两个不兼容类型的对象做位移操作（{operator}）：\n"
"{first} 和 {second}\n"
"不兼容的类型不能做位移操作。\n"

#: analyze_type_error.py:157
msgid ""
"You tried to exponentiate (raise to a power)\n"
"using two incompatible types of objects:\n"
"{first} and {second}\n"
msgstr ""
"你想把两个不兼容类型的对象做幂运算（**）：\n"
"{first} 和 {second}\n"
"不兼容的类型不能做幂运算。\n"

#: analyze_type_error.py:165
msgid ""
"You tried to use the operator {operator}\n"
"using two incompatible types of objects:\n"
"{first} and {second}.\n"
"This operator is normally used only\n"
"for multiplication of matrices.\n"
msgstr ""
"你想把两个不兼容类型的对象做（{operator}）运算：\n"
"{first} 和 {second}\n"
"但这种运算应该只用来做矩阵乘法。\n"

#: analyze_type_error.py:188
msgid ""
"You tried to do an order comparison ({operator})\n"
"between two incompatible types of objects:\n"
"{first} and {second}\n"
msgstr ""
"你想把两个不兼容类型的对象做（{operator}）顺序比较：\n"
"{first} 和 {second}\n"
"不兼容的类型不能做顺序比较。\n"

#: analyze_type_error.py:210
msgid ""
"You tried to use the unary operator '{operator}'\n"
"with the following type of object: {obj}.\n"
"This operation is not defined for this type of object.\n"
msgstr ""
"你想把{obj}类型的对象做单目运算’{operator}’\n"
"这种运算还没定义到这个类型上。\n"

#: analyze_type_error.py:227
msgid ""
"In Python, some objects are known as immutable:\n"
"once defined, their value cannot be changed.\n"
"You tried change part of such an immutable object: {obj},\n"
"most likely by using an indexing operation.\n"
msgstr ""
"Python语言里有些对象是“不可变类型”的，\n"
"一旦赋值好了以后，就不能改变。\n"
"你想修改{obj}类型包含的数据项，所以导致了错误。\n"

#: analyze_type_error.py:246
msgid ""
"You apparently have called the function '{fn_name}' with\n"
"{nb_given} positional argument while it requires {nb_required}\n"
"such positional arguments.\n"
msgstr ""
"你用{nb_given} 参数来调用了’{fn_name}’ 函数，\n"
"但这个函数需要 {nb_required}参数。\n"

#: analyze_type_error.py:266
msgid ""
"You apparently have called the function '{fn_name}' with\n"
"fewer positional arguments than it requires ({nb_required} missing).\n"
msgstr "你调用了“{fn_name}”函数，但忘了给{nb_required} 参数。\n"

#: analyze_type_error.py:281
msgid ""
"I suspect that you had an object of this type, <{obj}>,\n"
"followed by what looked like a tuple, '(...)',\n"
"which Python took as an indication of a function call.\n"
"Perhaps you had a missing comma before the tuple.\n"
msgstr ""
"我怀疑你在一个<{obj}>类型的对象后面直接跟了个元组’(…)’，\n"
"Python以为你在调用函数，\n"
"你可能是忘记了在元组前加个逗号“,”。\n"

#: core.py:354
msgid ""
"        I suspect that you are using a regular\n"
"        Python console after importing\n"
"Friendly-traceback.\n"
"        Unfortunately, no further processing can be done.\n"
msgstr ""

#: core.py:385
msgid ""
"Unfortunately, no additional information is available:\n"
"the content of file '<stdin>' is not accessible.\n"
"Are you using a regular Python console instead of a Friendly-console?\n"
msgstr ""

#: core.py:397
msgid ""
"Unfortunately, no additional information is available:\n"
"the content of file '<string>' is not accessible.\n"
msgstr ""
"我好像没什么头绪。\n"
"文件’<string>’没法访问。\n"

#: core.py:443
msgid "Exception raised on line {linenumber} of file '{filename}'.\n"
msgstr ""
"在源文件’{filename}’的第{linenumber} 行有例外被触发。\n"
"……就是出错了！\n"

#: core.py:536
msgid "I don't have enough information from Python:"
msgstr "我没能从Python得到足够信息来判断："

#: core.py:538
msgid "Likely cause based on the information given by Python:"
msgstr "从Python给的信息来看，可能是如下的原因："

#: core.py:580
msgid ""
"        To see the lines of code that cause the problem, \n"
"        you must use the Friendly Console and not a \n"
"        regular Python console.\n"
msgstr ""

#: core.py:586
msgid "Problem: source of '{filename}' is not available\n"
msgstr "问题：文件’{filename}’ 来源不可用\n"

#: core.py:601
msgid "Execution stopped on line {linenumber} of file '{filename}'.\n"
msgstr ""
"在源文件’{filename}’的第{linenumber}行执行中止了。\n"
"错误就在这行代码或者附近！\n"

#: core.py:615
msgid ""
"Python could not understand the code in the file\n"
"'{filename}'\n"
"beyond the location indicated below by --> and ^.\n"
msgstr ""
"Python无法解释文件’{filename}’里的代码，\n"
"看看 —>和 ^ 指示下面的地方？\n"

#: core.py:621
msgid ""
"Python could not understand the code the file\n"
"'{filename}'.\n"
"It reached the end of the file and expected more content.\n"
msgstr ""
"Python无法解释文件’{filename}’里的代码，\n"
"文件到末尾了，但应该还有别的内容。\n"

#: core.py:627
msgid ""
"Python could not understand the code the file\n"
"'{filename}'\n"
"for an unspecified reason.\n"
msgstr ""
"Python无法解释文件’{filename}’里的代码，\n"
"原因就是很奇怪。\n"

#: core.py:711
msgid "Python exception:"
msgstr "Python给的消息："

#: friendly_exception.py:10
msgid ""
"Friendly-traceback: Internal Problem\n"
"Source: {fn_name}\n"
"Please report this case.\n"
msgstr ""

#: info_generic.py:27
msgid ""
"ArithmeticError is the base class for those built-in exceptions\n"
"that are raised for various arithmetic errors.\n"
"It is unusual that you are seeing this exception;\n"
"normally, a more specific exception should have been raised.\n"
msgstr ""

#: info_generic.py:38
msgid ""
"A FileNotFoundError exception indicates that you\n"
"are trying to open a file that cannot be found by Python.\n"
"This could be because you misspelled the name of the file.\n"
msgstr ""
"FileNotFoundError这个错误表示你想让Python打开一个无法找到的文件。\n"
"可能是你把文件名或者目录名给写错了？\n"

#: info_generic.py:48
msgid ""
"This exception indicates that a certain object could not\n"
"be imported from a module or package. Most often, this is\n"
"because the name of the object is not spelled correctly.\n"
msgstr "你可能写错对象的名称，导致无法import。\n"

#: info_generic.py:58
msgid ""
"An IndentationError occurs when a given line of code is\n"
"not indented (aligned vertically with other lines) as expected.\n"
msgstr ""
"IndentationError是说代码的缩进有错，\n"
"再检查一下：\n"
"- 缩进的空格数是不是一致？会不会有的4个空格有的只有3个或者5个？\n"
"- if、for、while、def这些语句，最后有冒号的，但下一行没缩进？\n"

#: info_generic.py:67
msgid ""
"An IndexError occurs when you are try to get an item from a list,\n"
"a tuple, or a similar object (sequence), by using an index which\n"
"does not exists; typically, this is because the index you give\n"
"is greater than the length of the sequence.\n"
"Reminder: the first item of a sequence is at index 0.\n"
msgstr ""
"IndexError这个错误是列表、字符串或者元组下标越界了，\n"
"一般可能是你给的下标超过了最后一个元素。\n"
"注意：第一个元素的下标是0哟。\n"

#: info_generic.py:79
msgid ""
"A KeyError is raised when a value is not found as a\n"
"key in a Python dict.\n"
msgstr "KeyError错误是因为你引用了字典里不存在的一个键（key）。\n"

#: info_generic.py:88
msgid ""
"LookupError is the base class for the exceptions that are raised\n"
"when a key or index used on a mapping or sequence is invalid.\n"
"It can also be raised directly by codecs.lookup().\n"
msgstr ""

#: info_generic.py:98
msgid ""
"A ModuleNotFoundError exception indicates that you\n"
"are trying to import a module that cannot be found by Python.\n"
"This could be because you misspelled the name of the module\n"
"or because it is not installed on your computer.\n"
msgstr ""
"ModuleNotFoundError错误是说你想import一个不存在的模块。\n"
"一般是因为你还没给Python解释器安装这个包，\n"
"或者是写错了模块的名称。\n"

#: info_generic.py:109
msgid ""
"A NameError exception indicates that a variable or\n"
"function name is not known to Python.\n"
"Most often, this is because there is a spelling mistake.\n"
"However, sometimes it is because the name is used\n"
"before being defined or given a value.\n"
msgstr ""
"NameError错误是指Python无法理解你给的变量或者函数的名称。\n"
"一般来说是：\n"
"- 你写错了名称？\n"
"- 大小写弄错了？\n"
"- 还没给变量赋值？\n"
"- 还没定一这个函数？\n"

#: info_generic.py:121
msgid ""
"An OverflowError is raised when the result of an arithmetic operation\n"
"is too large to be handled by the computer's processor.\n"
msgstr "OverflowError就是算术运算溢出了，不知道你哪弄的这么大的数？\n"

#: info_generic.py:130
msgid "A SyntaxError occurs when Python cannot understand your code.\n"
msgstr ""
"SyntaxError就是语法错误，可能是因为写错了关键字，大小写搞错？\n"
"if、while、for、def这样的语句忘记加冒号（:）了？\n"

#: info_generic.py:136
msgid ""
"A TabError indicates that you have used both spaces\n"
"and tab characters to indent your code.\n"
"This is not allowed in Python.\n"
"Indenting your code means to have block of codes aligned vertically\n"
"by inserting either spaces or tab characters at the beginning of lines.\n"
"Python's recommendation is to always use spaces to indent your code.\n"
msgstr ""
"TabError错误是因为你在缩进的时候混用了空格和TAB键，\n"
"一个源文件里要么都是空格缩进，要么都是TAB缩进，\n"
"Python建议都用空格来缩进代码。\n"

#: info_generic.py:149
msgid ""
"A TypeError is usually caused by trying\n"
"to combine two incompatible types of objects,\n"
"by calling a function with the wrong type of object,\n"
"or by tring to do an operation not allowed on a given type of object.\n"
msgstr ""
"TypeError这个错误通常是你把两个不同类型的对象放在一起运算了。\n"
"或者函数调用的参数给错类型，\n"
"或者把对象类型搞错了，做了一个其它类型才能做的操作。\n"

#: info_generic.py:160
msgid ""
"A ValueError indicates that a function or an operation\n"
"received an argument of the right type, but an inappropriate value.\n"
msgstr "ValueError错误一般是说你给的对象，类型是对的，但具体的值不对。\n"

#: info_generic.py:169
msgid ""
"In Python, variables that are used inside a function are known as \n"
"local variables. Before they are used, they must be assigned a value.\n"
"A variable that is used before it is assigned a value is assumed to\n"
"be defined outside that function; it is known as a 'global'\n"
"(or sometimes 'nonlocal') variable. You cannot assign a value to such\n"
"a global variable inside a function without first indicating to\n"
"Python that this is a global variable, otherwise you will see\n"
"an UnboundLocalError.\n"
msgstr ""
"在Python里，函数内部的变量称为“局部变量”。\n"
"局部变量也一样需要先赋值才能使用。\n"
"\n"
"在函数内部，如果不先赋值就直接引用一个变量，Python会到函数外部去找它，\n"
"这种函数外部的变量称为“全局变量”。\n"
"\n"
"在函数里，必须用global语句来声明一个全局变量，才能给全局变量赋值，\n"
"否则会出错，错误名称是：UnboundLocalError\n"

#: info_generic.py:184
msgid ""
"No information is known about this exception.\n"
"Please report this example to\n"
"https://github.com/aroberge/friendly-traceback/issues\n"
msgstr "对此错误，我们不知道咋回事……\n"

#: info_generic.py:194
msgid ""
"A ZeroDivisionError occurs when you are attempting to divide\n"
"a value by zero:\n"
"    result = my_variable / 0\n"
"It can also happen if you calculate the remainder of a division\n"
"using the modulo operator '%'\n"
"    result = my_variable % 0\n"
msgstr ""
"ZeroDivisionError这个错误通常是你想把0作为被除数：\n"
"    result = my_variable / 0\n"
"或者求余数：\n"
"result = my_variable % 0\n"
"\n"
"当然，一般不会这么明显写个0上去，估计是作为被除数的变量意外变成0了！\n"

#: info_specific.py:36
msgid ""
"In your program, the name of the\n"
"file that cannot be found is '{filename}'.\n"
msgstr ""
"你这段程序找不到的文件，名字叫做：\n"
"‘{filename}’\n"

#: info_specific.py:55
msgid ""
"The object that could not be imported is '{name}'.\n"
"The module or package where it was \n"
"expected to be found is '{module}'.\n"
msgstr ""
"无法导入的对象名字叫做：’{name}’。\n"
"你可能想从’{module}’这个模块导入它。\n"

#: info_specific.py:61
msgid "The object that could not be imported is '{name}'.\n"
msgstr ""
"无法导入的对象名字叫做：’{name}’。\n"
"\n"

#: info_specific.py:72
msgid ""
"In this case, the line identified above\n"
"is more indented than expected and \n"
"does not match the indentation of the previous line.\n"
msgstr "你这个情况可能是缩进太多了，跟上面一行没有对齐。\n"

#: info_specific.py:78
msgid ""
"In this case, the line identified above\n"
"was expected to begin a new indented block.\n"
msgstr "你这个情况可能是忘了缩进。\n"

#: info_specific.py:83
msgid ""
"In this case, the line identified above is\n"
"less indented than the preceding one,\n"
"and is not aligned vertically with another block of code.\n"
msgstr "你这个情况可能是忘记了缩进，没有跟一起的代码块对齐。\n"

#: info_specific.py:96
msgid "In this case, the sequence is a list.\n"
msgstr "你这个情况是一个列表（list）。\n"

#: info_specific.py:98
msgid "In this case, the sequence is a tuple.\n"
msgstr "你这个情况是一个元组（tuple）。\n"

#: info_specific.py:112
msgid ""
"In your program, the name of the key\n"
"that cannot be found is '{key_name}'.\n"
msgstr "你程序里这个找不到的key是：’{key_name}’。\n"

#: info_specific.py:126
msgid ""
"In your program, the name of the\n"
"module that cannot be found is '{mod_name}'.\n"
msgstr "你程序里这个找不到的模块是：’{mod_name}’。\n"

#: info_specific.py:140
msgid "In your program, the unknown name is '{var_name}'.\n"
msgstr "你程序里这个未知的名称是：’{var_name}’。\n"

#: info_specific.py:168
msgid ""
"The variable that appears to cause the problem is '{var_name}'.\n"
"Perhaps the statement\n"
"    global {var_name}\n"
"should have been included as the first line inside your function.\n"
msgstr ""
"搞出错误的变量名是：’{var_name}’。\n"
"可能你该把这个语句：\n"
"    global {var_name}\n"
"放在函数的第一行才行。\n"

#: line_analyzer.py:102
msgid ""
"You appear to be using the operator :=, sometimes called\n"
"the walrus operator. This operator requires the use of\n"
"Python 3.8 or newer. You are using version {version}.\n"
msgstr ""
"你好像在用“:=”这个操作符，但这是Python 3.8才有的符号。\n"
"你现在用的Python版本是：{version}。\n"

#: line_analyzer.py:119
msgid ""
"You are using the backquote character `.\n"
"This was allowed in Python 2 but is no longer allowed.\n"
"Use the function repr(x) instead of `x`."
msgstr ""
"你在用反引号：“`”\n"
"这个在Python3里不能用了，要用就用：\n"
"\n"
"repr(x)\n"
"\n"
"来代替你这个`x`。"

#: line_analyzer.py:134 message_analyzer.py:82
msgid ""
"You were trying to assign a value to the Python keyword '{keyword}'.\n"
"This is not allowed.\n"
"\n"
msgstr ""
"你把Python的关键字’{keyword}’拿来做变量赋值了，关键字不能做变量用。\n"
"\n"

#: line_analyzer.py:150
msgid ""
"You meant to use Python's 'elif' keyword\n"
"but wrote '{name}' instead\n"
"\n"
msgstr ""
"你可能想用Python的elif语句，\n"
"可是，写成了’{name}’。\n"
"\n"

#: line_analyzer.py:169
msgid ""
"You wrote something like\n"
"    import {function} from {module}\n"
"instead of\n"
"    from {module} import {function}\n"
"\n"
msgstr ""
"你写了：\n"
"    import {function} from {module}\n"
"其实应该是这样：\n"
"    from {module} import {function}\n"
"\n"

#: line_analyzer.py:187
msgid ""
"You cannot use the Python keyword {word} as an attribute.\n"
"\n"
msgstr ""
"你不能把Python的关键字（保留字）{word} 作为属性或者变量来用。\n"
"\n"

#: line_analyzer.py:191
msgid ""
"You cannot use the constant __debug__ as an attribute.\n"
"\n"
msgstr ""

#: line_analyzer.py:210
msgid ""
"There appears to be a Python identifier (variable name)\n"
"immediately following a string.\n"
"I suspect that you were trying to use a quote inside a string\n"
"that was enclosed in quotes of the same kind.\n"
msgstr ""
"好像有一个变量直接跟在字符串后面了，\n"
"你是不是想把它俩连接起来？\n"
"这样？\n"
"f\"Hello, {myname}\"\n"

#: line_analyzer.py:233
msgid "a class"
msgstr "1个类（“class”）"

#: line_analyzer.py:234
msgid ""
"You wanted to define {class_}\n"
"but forgot to add a colon ':' at the end\n"
"\n"
msgstr "你想定义一个类{class_}，但忘记在语句最后加个冒号（:）\n"

#: line_analyzer.py:240
msgid ""
"You wrote a '{for_while}' loop but\n"
"forgot to add a colon ':' at the end\n"
"\n"
msgstr "你想写一个'{for_while}'循环，但是忘了在语句最后加个冒号了（:）\n"

#: line_analyzer.py:246
msgid ""
"You wrote a statement beginning with\n"
"'{name}' but forgot to add a colon ':' at the end\n"
"\n"
msgstr "你写了一个'{name}’开始的语句，但是忘了在语句最后加个冒号了（:）。\n"

#: line_analyzer.py:272
msgid "a function or method"
msgstr "1个函数或者方法（function/method）"

#: line_analyzer.py:273
msgid ""
"You tried to define {class_or_function} and did not use the correct syntax.\n"
"The correct syntax is:\n"
"    def name ( optional_arguments ):\n"
msgstr ""
"你可能想定义 {class_or_function} 函数或者类，但语法用错了。\n"
"正确的定义语句是：\n"
"    def name ( optional_arguments ):\n"

#: line_analyzer.py:282
msgid "You tried to use the Python keyword '{kwd}' as a function name.\n"
msgstr ""
"你想把Python关键字（保留字）'{kwd}'拿来做函数名，关键字不能做别的用。\n"

#: line_analyzer.py:329
msgid ""
"I am guessing that you tried to use the Python keyword\n"
"{kwd} as an argument in the definition of a function.\n"
msgstr ""
"我猜你可能是想把Python关键字（保留字）{kwd}拿来做函数的参数定义，关键字不能这"
"么用。\n"

#: message_analyzer.py:78
msgid ""
"{keyword} is a constant in Python; you cannot assign it a value.\n"
"\n"
msgstr "{keyword}是Python的关键字（保留字），不能把它当变量赋值。\n"

#: message_analyzer.py:96
msgid ""
"On the left-hand side of an equal sign, you have a\n"
"conditional expression instead of the name of a variable.\n"
"A conditional expression has the following form:\n"
"\n"
"    variable = object if condition else other_object"
msgstr ""
"在等号（=）左边，你好像写了一个条件表达式，而不是变量名。\n"
"那种三元表达式（三目运算符）是这么写：\n"
"   变量= 值1 if 条件 else 值2\n"
"比如这样：\n"
"    a = \"big\" if n>999 else \"small”"

#: message_analyzer.py:115
msgid "my_function(...)"
msgstr ""

#: message_analyzer.py:116
msgid "some value"
msgstr "某些值"

#: message_analyzer.py:117
msgid ""
"You wrote an expression like\n"
"    {fn_call} = {value}\n"
"where {fn_call}, on the left-hand side of the equal sign, is\n"
"a function call and not the name of a variable.\n"
msgstr ""
"你写了一个这样的表达式：\n"
"    {fn_call} = {value}\n"
"等号左边的这个{fn_call}，是个函数调用，\n"
"等号左边应该是个变量才对。\n"

#: message_analyzer.py:127
msgid ""
"You wrote the expression\n"
"    {fn_call} = {value}\n"
"where {fn_call}, on the left-hand side of the equal sign, either is\n"
"or includes a function call and is not simply the name of a variable.\n"
msgstr ""
"你写了一个这样的表达式：\n"
"    {fn_call} = {value}\n"
"等号左边的这个{fn_call}，应该是个变量才对。\n"

#: message_analyzer.py:142
msgid ""
"On the left-hand side of an equal sign, you have a\n"
"generator expression instead of the name of a variable.\n"
msgstr "等号左边你写了一个生成器表达式，这里应该是个变量才对。\n"

#: message_analyzer.py:157
msgid "of type 'int'"
msgstr "（int整数类型）"

#: message_analyzer.py:159
msgid "of type 'str'"
msgstr "（str字符串类型）"

#: message_analyzer.py:161
msgid "of type 'float'"
msgstr "（float浮点数类型）"

#: message_analyzer.py:163
msgid "of type 'complex'"
msgstr "（complex复数类型）"

#: message_analyzer.py:165
msgid "of type 'dict'"
msgstr "（dict字典类型）"

#: message_analyzer.py:167
msgid "of type 'tuple'"
msgstr "（tuple元组类型）"

#: message_analyzer.py:169
msgid "of type 'list'"
msgstr "（list列表类型）"

#: message_analyzer.py:171
msgid "of type 'set'"
msgstr "（set集合类型）"

#: message_analyzer.py:191
msgid "variable_name"
msgstr "变量名"

#: message_analyzer.py:195
msgid ""
" Perhaps you meant to write:\n"
"    {name} = {literal}\n"
"\n"
msgstr ""
" 你可能是想写这个：\n"
"    {name} = {literal}\n"
"\n"

#: message_analyzer.py:218
msgid ""
"You wrote an expression like\n"
"    {literal} = {name}\n"
"where <{literal}>, on the left-hand side of the equal sign,\n"
"is or includes an actual object {of_type}\n"
"and is not simply the name of a variable."
msgstr ""
"你写了一个这样的表达式：\n"
"    {literal} = {name}\n"
"可是这个{literal} 在等号左边，可能是个{of_type}类型的对象，\n"
"但等号左边应该是一个变量才对。"

#: message_analyzer.py:236
msgid ""
"You wrote an expression that includes some mathematical operations\n"
"on the left-hand side of the equal sign which should be\n"
"only used to assign a value to a variable."
msgstr "你在赋值的等号左边写了一些算术符号，但等号左边只能是一个变量。"

#: message_analyzer.py:247
msgid ""
"The Python keyword 'break' can only be used inside a for loop or inside a "
"while loop.\n"
msgstr "Python的break只能在for循环或者while循环里用。\n"

#: message_analyzer.py:257
msgid ""
"The Python keyword 'continue' can only be used inside a for loop or inside a "
"while loop.\n"
msgstr "Python的continue只能在for循环或者while循环里用。\n"

#: message_analyzer.py:281
msgid ""
"You attempted to delete a function call\n"
"    {line}\n"
"instead of deleting the function's name\n"
"    {correct}\n"
msgstr ""
"你想删除一个函数调用？\n"
"    {line}\n"
"这是办不到的，可能你只是想删除这个函数，应该这样：\n"
"    {correct}\n"

#: message_analyzer.py:293
msgid ""
"You starting writing a string with a single or double quote\n"
"but never ended the string with another quote on that line.\n"
msgstr "你的字符串左引号和右边的引号不配对呀。\n"

#: message_analyzer.py:303
msgid ""
"One of the following two possibilities could be the cause:\n"
"1. You meant to do a comparison with == and wrote = instead.\n"
"2. You called a function with a named argument:\n"
"\n"
"       a_function(invalid=something)\n"
"\n"
"where 'invalid' is not a valid variable name in Python\n"
"either because it starts with a number, or is a string,\n"
"or contains a period, etc.\n"
"\n"
msgstr ""
"根据分析，你有下面两种可能错误之一：\n"
"1，你想做相等的判断，结果只写了“=”，应该是“==”；\n"
"2，或者，你用命名参数来调用函数：\n"
"\n"
"a_function(invalid=something)\n"
"\n"
"可是这个参数名写错了，它不是一个有效的名称，比如数字开头之类的。\n"

#: message_analyzer.py:319
msgid ""
"You likely called a function with a named argument:\n"
"\n"
"   a_function(invalid=something)\n"
"\n"
"where 'invalid' is not a valid variable name in Python\n"
"either because it starts with a number, or is a string,\n"
"or contains a period, etc.\n"
"\n"
msgstr ""
"你好像在用命名参数来调用函数：\n"
"\n"
"a_function(invalid=something)\n"
"\n"
"可是这个参数名写错了，它不是一个有效的名称，比如数字开头之类的。\n"

#: message_analyzer.py:333
msgid ""
"You likely used some unicode character that is not allowed\n"
"as part of a variable name in Python.\n"
"This includes many emojis.\n"
"\n"
msgstr ""
"很多unicode字符都可以放在变量名里，比如中文字符。\n"
"但你好像把表情符号加到变量名了？这些符号是没法做变量名的。\n"

#: message_analyzer.py:367
msgid ""
"Python tells us that the closing '{closing}' on the last line shown\n"
"does not match the opening '{opening}' on line {lineno}.\n"
"\n"
msgstr ""
"Python说上一行代码里的右括号’{closing}’不匹配第{lineno}行里的左括"
"号’{opening}’。\n"

#: message_analyzer.py:372
msgid ""
"Python tells us that the closing '{closing}' on the last line shown\n"
"does not match the opening '{opening}'.\n"
"\n"
msgstr "Python说上一行代码里的右括号’{closing}’不匹配左括号’{opening}’。\n"

#: message_analyzer.py:383
msgid ""
"I will attempt to be give a bit more information.\n"
"\n"
msgstr "我尽量给更多些提示。\n"

#: message_analyzer.py:394
msgid ""
"Inside an f-string, which is a string prefixed by the letter f, \n"
"you have another string, which starts with either a\n"
"single quote (') or double quote (\"), without a matching closing one.\n"
msgstr ""
"Python里，f-string是f开头后面紧跟一个字符串。\n"
"你这个字符串似乎少了个右引号呢。\n"
"\n"

#: message_analyzer.py:411
msgid ""
"You are including the statement\n"
"\n"
"    {newline}\n"
"\n"
"indicating that '{name}' is a variable defined outside a function.\n"
"You are also using the same '{name}' as an argument for that\n"
"function, thus indicating that it should be variable known only\n"
"inside that function, which is the contrary of what 'global' implied.\n"
msgstr ""
"你写了这样的语句：\n"
"\n"
"    {newline}\n"
"\n"
"这里 ‘{name}’ 是在函数之外定义的变量，但你还把 ‘{name}’ 用来作为函数的参"
"数，\n"
"这样的话，它只能是一个局部变量，而不能作为全局变量用。\n"

#: message_analyzer.py:427
msgid ""
"You assigned a value to the variable '{name}'\n"
"before declaring it as a global variable.\n"
msgstr ""
"你给变量’{name}’赋值，但还没声明它是个全局变量。\n"
"或者可能用错变量了？\n"

#: message_analyzer.py:439
msgid ""
"You used the variable '{name}'\n"
"before declaring it as a global variable.\n"
msgstr "你在声明’{name}’是个全局变量之前，就用了它。\n"

#: message_analyzer.py:451
msgid ""
"You assigned a value to the variable '{name}'\n"
"before declaring it as a nonlocal variable.\n"
msgstr ""
"你给变量’{name}’赋值，但它是个非局部变量。\n"
"或者可能用错变量了？\n"

#: message_analyzer.py:462
msgid ""
"You used '{name}' as a parameter for a function\n"
"before declaring it also as a nonlocal variable:\n"
"'{name}' cannot be both at the same time.\n"
msgstr ""
"你把函数的参数’{name}’声明成非局部变量（全局变量）\n"
"函数参数’{name}’不能既是参数又是非局部变量，它一定是局部变量。\n"

#: message_analyzer.py:475
msgid ""
"You used the variable '{name}'\n"
"before declaring it as a nonlocal variable.\n"
msgstr "你用了变量（{name}），但没用global声明它是个非局部变量（全局变量）。\n"

#: message_analyzer.py:485
msgid ""
"You are using the continuation character '\\' outside of a string,\n"
"and it is followed by some other character(s).\n"
"I am guessing that you forgot to enclose some content in a string.\n"
"\n"
msgstr ""
"你把转义符“\\”放在字符串外面了，后面还跟了一些其它字符。\n"
"我觉得你是定义字符串的时候忘了点什么内容。\n"

#: message_analyzer.py:501
msgid ""
"Python tells us that the it reached the end of the file\n"
"and expected more content.\n"
"\n"
"I will attempt to be give a bit more information.\n"
"\n"
msgstr ""
"Python说它把源代码文件执行到底了，但还缺一些语句啊。\n"
"\n"
"我看看能不能给多一些信息。\n"

#: message_analyzer.py:525 source_analyzer.py:84
msgid "The closing {bracket} on line {linenumber} does not match anything.\n"
msgstr ""
"在第{linenumber}行代码里的这个右括号“{bracket}”找不到对应的左括号，是不是多余"
"了？\n"

#: message_analyzer.py:535
msgid ""
"In Python, you can call functions with only positional arguments\n"
"\n"
"    test(1, 2, 3)\n"
"\n"
"or only keyword arguments\n"
"\n"
"    test(a=1, b=2, c=3)\n"
"\n"
"or a combination of the two\n"
"\n"
"    test(1, 2, c=3)\n"
"\n"
"but with the keyword arguments appearing after all the positional ones.\n"
"According to Python, you used positional arguments after keyword ones.\n"
msgstr ""
"在Python里，调用函数可以全部用位置参数：\n"
"\n"
"    test(1, 2, 3)\n"
"\n"
"也可以全部用命名参数：\n"
"\n"
"    test(a=1, b=2, c=3)\n"
"\n"
"但是在两种参数混用的时候：\n"
"\n"
"    test(1, 2, c=3)\n"
"\n"
"命名参数必须要放在最后，位置参数在前。\n"
"你可能把位置参数放到命名参数后面了。\n"

#: message_analyzer.py:552
msgid ""
"In Python, you can define functions with only positional arguments\n"
"\n"
"    def test(a, b, c): ...\n"
"\n"
"or only keyword arguments\n"
"\n"
"    def test(a=1, b=2, c=3): ...\n"
"\n"
"or a combination of the two\n"
"\n"
"    def test(a, b, c=3): ...\n"
"\n"
"but with the keyword arguments appearing after all the positional ones.\n"
"According to Python, you used positional arguments after keyword ones.\n"
msgstr ""
"在Python里，你可以定义一个只有位置参数的函数：\n"
"\n"
"    def test(a, b, c): …\n"
"\n"
"或者，只有命名参数的函数：\n"
"\n"
"    def test(a=1, b=2, c=3): …\n"
"\n"
"但是，如果要混用这两种参数的话：\n"
"\n"
"    def test(a, b, c=3): …\n"
"\n"
"就必须把命名参数放最后，位置参数放前面。\n"
"你可能把位置参数放到命名参数后面了。\n"

#: message_analyzer.py:572
msgid ""
"Perhaps you need to type print({message})?\n"
"\n"
"In older version of Python, 'print' was a keyword.\n"
"Now, 'print' is a function; you need to use parentheses to call it.\n"
msgstr ""
"在Python3里，print是一个函数，需要用print(a)这样，加一个括号来调用。\n"
"你可能忘记加括号了。\n"

#: session.py:103
msgid "Level {level} not available; using default."
msgstr ""

#: source_analyzer.py:108
msgid ""
"The closing {bracket} on line {close_lineno} does not match the opening "
"{open_bracket} on line {open_lineno}.\n"
msgstr ""
"第{close_lineno}行代码里的右括号“{bracket}”，不匹配第{open_lineno}行代码的那"
"个左括号“{open_bracket}”。\n"

#: source_analyzer.py:170
msgid ""
"It is possible that you used an equal sign '=' instead of a colon ':'\n"
"to assign values to keys in a dict\n"
"before or at the position indicated by --> and ^.\n"
msgstr ""
"你这行代码可能用“=”来给字典里的key和value做对应，字典里应该用冒号“:”来对"
"应：\n"
"adict = {\"name\":\"Tom\", \"age\":25}\n"

#: source_analyzer.py:214
msgid ""
"It is possible that you forgot a comma between items in a tuple, \n"
"or between function arguments, \n"
"before the position indicated by --> and ^.\n"
msgstr ""
"在 —> 和 ^ 所指示的位置，\n"
"你可能忘了在函数参数之间加逗号，\n"
"或者也可能是个元组的元素之间没有逗号。\n"

#: source_analyzer.py:221
msgid ""
"It is possible that you forgot a comma between items in a list\n"
"before the position indicated by --> and ^.\n"
msgstr ""
"在 —> 和 ^ 所指示的位置，\n"
"你想处理列表，但是忘了在元素之间加逗号。\n"

#: source_analyzer.py:227
msgid ""
"It is possible that you forgot a comma between items in a set or dict\n"
"before the position indicated by --> and ^.\n"
msgstr ""
"在 —> 和 ^ 所指示的位置，\n"
"你想处理集合或者字典，但是忘了在元素之间加逗号。\n"

#: source_analyzer.py:238
msgid "The opening {bracket} on line {linenumber} is not closed.\n"
msgstr "在第{linenumber}行，左括号{bracket}没有对应的右括号。\n"

#: source_analyzer.py:258
msgid "parenthesis '('"
msgstr "圆括号 ‘(‘"

#: source_analyzer.py:260
msgid "parenthesis ')'"
msgstr "圆括号 ‘)‘"

#: source_analyzer.py:262
msgid "square bracket '['"
msgstr "方括号 ‘[‘"

#: source_analyzer.py:264
msgid "square bracket ']'"
msgstr "方括号 ‘]‘"

#: source_analyzer.py:266
msgid "curly bracket '{'"
msgstr "花括号 ‘{‘"

#: source_analyzer.py:268
msgid "curly bracket '}'"
msgstr "花括号 ‘}‘"
